server:
  port: 8000
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/uaa
    username: user
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hubernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect