version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PWD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"

volumes:
  db: 